/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Funcinarios;

import View.HomePageScreen;
import View.PainelBackUp.BackUpScreen;
import View.VendaScreen;
import View.produto.GerenciarProdutos;
import dao.FuncionarioDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juanb
 */
public class GerenciarFuncionarios extends javax.swing.JFrame {

    /**
     * Creates new form BuscaFuncionario
     */
    public GerenciarFuncionarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BuscarFunScreen = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        IdPesquisa = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        NomeFunPesquisa = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        FunTable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        UpdatesPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        senhaUpdate = new javax.swing.JTextPane();
        UpdateBtn = new javax.swing.JButton();
        jScrollPane11 = new javax.swing.JScrollPane();
        NomeUpdate = new javax.swing.JTextPane();
        jScrollPane12 = new javax.swing.JScrollPane();
        CpfUpdate = new javax.swing.JTextPane();
        jLabel11 = new javax.swing.JLabel();
        DeleteBtn = new javax.swing.JButton();
        FunId = new javax.swing.JLabel();
        FuncUpdate = new javax.swing.JComboBox<>();
        atualFun = new javax.swing.JLabel();
        revokeFunc = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        homeBtn = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        MenuFunc = new javax.swing.JMenu();
        MenuGerenciarFunc = new javax.swing.JMenuItem();
        MenuCadastrarFunc = new javax.swing.JMenuItem();
        backupBtn = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel8.setText("Buscar por nome: ");

        jLabel9.setText("Buscar por ID: ");

        jScrollPane6.setViewportView(IdPesquisa);

        jScrollPane7.setViewportView(NomeFunPesquisa);

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        FunTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF", "Senha", "Funcao"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        FunTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FunTableMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(FunTable);

        jButton2.setBackground(new java.awt.Color(102, 102, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Listar Todos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        UpdatesPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setText("Nome: ");

        jLabel12.setText("CPF: ");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Nova senha: ");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Alterar Função: ");

        jScrollPane10.setViewportView(senhaUpdate);

        UpdateBtn.setBackground(new java.awt.Color(0, 153, 51));
        UpdateBtn.setForeground(new java.awt.Color(255, 255, 255));
        UpdateBtn.setText("Salvar Alterações");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });

        jScrollPane11.setViewportView(NomeUpdate);

        jScrollPane12.setViewportView(CpfUpdate);

        jLabel11.setText("Código");

        DeleteBtn.setBackground(new java.awt.Color(204, 0, 0));
        DeleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        DeleteBtn.setText("Deletar");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        FuncUpdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "gerente", "funcionario", "admin" }));
        FuncUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FuncUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UpdatesPanelLayout = new javax.swing.GroupLayout(UpdatesPanel);
        UpdatesPanel.setLayout(UpdatesPanelLayout);
        UpdatesPanelLayout.setHorizontalGroup(
            UpdatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdatesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UpdatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FuncUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(UpdatesPanelLayout.createSequentialGroup()
                        .addGroup(UpdatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(UpdatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FunId, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(UpdatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, UpdatesPanelLayout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(revokeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(atualFun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, UpdatesPanelLayout.createSequentialGroup()
                            .addComponent(UpdateBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(DeleteBtn))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        UpdatesPanelLayout.setVerticalGroup(
            UpdatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdatesPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(UpdatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(FunId, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(UpdatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane11)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UpdatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UpdatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(atualFun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(revokeFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FuncUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(UpdatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateBtn)
                    .addComponent(DeleteBtn))
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout BuscarFunScreenLayout = new javax.swing.GroupLayout(BuscarFunScreen);
        BuscarFunScreen.setLayout(BuscarFunScreenLayout);
        BuscarFunScreenLayout.setHorizontalGroup(
            BuscarFunScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscarFunScreenLayout.createSequentialGroup()
                .addGroup(BuscarFunScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BuscarFunScreenLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(BuscarFunScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BuscarFunScreenLayout.createSequentialGroup()
                                .addGroup(BuscarFunScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(BuscarFunScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(BuscarFunScreenLayout.createSequentialGroup()
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1))))
                            .addGroup(BuscarFunScreenLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(BuscarFunScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(BuscarFunScreenLayout.createSequentialGroup()
                                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49)
                                        .addComponent(UpdatesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(BuscarFunScreenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        BuscarFunScreenLayout.setVerticalGroup(
            BuscarFunScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BuscarFunScreenLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(BuscarFunScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BuscarFunScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BuscarFunScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdatesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(313, 313, 313))
        );

        homeBtn.setText("Home");
        homeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeBtnMouseClicked(evt);
            }
        });
        jMenuBar1.add(homeBtn);

        jMenu2.setText("Vendas ");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Produtos");

        jMenu5.setText("Gerenciar");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenu3.add(jMenu5);

        jMenuBar1.add(jMenu3);

        MenuFunc.setText("Gerenciamento");

        MenuGerenciarFunc.setText("Gerenciar Funcionarios ");
        MenuGerenciarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuGerenciarFuncActionPerformed(evt);
            }
        });
        MenuFunc.add(MenuGerenciarFunc);

        MenuCadastrarFunc.setText("Cadastrar  Funcionarios");
        MenuCadastrarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadastrarFuncActionPerformed(evt);
            }
        });
        MenuFunc.add(MenuCadastrarFunc);

        backupBtn.setText("Back Up");
        backupBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backupBtnMouseClicked(evt);
            }
        });
        MenuFunc.add(backupBtn);

        jMenuBar1.add(MenuFunc);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 888, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(BuscarFunScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 543, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(BuscarFunScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //Botão para pesquisar por nome ou ID
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String nomeInput = NomeFunPesquisa.getText();
        String idInput =  IdPesquisa.getText();

        DefaultTableModel table = (DefaultTableModel) FunTable.getModel();

        FuncionarioDAO funDao = new FuncionarioDAO();

        if(nomeInput.isEmpty() && idInput.isEmpty()){
            JOptionPane.showMessageDialog(
                null, "Algum campo precisa ser preenchido","Parâmetros incorretos"
                , JOptionPane.ERROR_MESSAGE);
        }else if(!nomeInput.isEmpty() && idInput.isEmpty()){

            table.setRowCount(0);
            funDao.buscarPorNome(nomeInput, table);
            System.out.print(nomeInput);
            NomeFunPesquisa.setText("");

        }else{
            table.setRowCount(0);
            int codigo = Integer.parseInt(idInput);
            funDao.buscarPorId(codigo, table);
            IdPesquisa.setText("");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    
    //pega a linha que foi clicada na tabela
    private void FunTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FunTableMouseClicked

        //pega a linha da tabela que foi selecionada
        int row = FunTable.getSelectedRow();

        //pega a tabela
        DefaultTableModel table = (DefaultTableModel) FunTable.getModel();

        String id = table.getValueAt(row, 0).toString();
        FunId.setText(id);

        //Pega os dados da tabela e add ao campo de alteração
        String nome = table.getValueAt(row, 1).toString();
        NomeUpdate.setText(nome);

        String cpf = table.getValueAt(row, 2).toString();
        CpfUpdate.setText(cpf);

        String senha = table.getValueAt(row, 3).toString();
        senhaUpdate.setText(senha);

        String funcao = table.getValueAt(row, 4).toString();
        FuncUpdate.setSelectedItem(funcao);
        
        revokeFunc.setText(funcao);

    }//GEN-LAST:event_FunTableMouseClicked


    //Botão para llistar todos
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        //pegando a tabela
        DefaultTableModel table = (DefaultTableModel) FunTable.getModel();

        //se tiver algum dado limpa a tabela e preenche novamente
        if(table.getRowCount() > 0){
            table.setRowCount(0);
        }

        FuncionarioDAO funDao = new FuncionarioDAO();

        funDao.listarFuncionarios(table);
    }//GEN-LAST:event_jButton2ActionPerformed

    //Botão de salvar alterações
    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed

        //pega os dados para serem editados
        int id = Integer.parseInt(FunId.getText());
        String nome = NomeUpdate.getText();
        String cpf = CpfUpdate.getText();
        String senha = senhaUpdate.getText();
        String funcao = (String) FuncUpdate.getSelectedItem();
        String revoke = revokeFunc.getText();

        //chama função para editar Funcionario
        FuncionarioDAO FunDao = new FuncionarioDAO();
        FunDao.editarFuncionario(id, nome, cpf, senha, funcao, revoke);

        DefaultTableModel table = (DefaultTableModel) FunTable.getModel();
        FunDao.listarFuncionarios(table);
    }//GEN-LAST:event_UpdateBtnActionPerformed

    //Botão de deletar funcionario
    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        // TODO add your handling code here:

        int id = Integer.parseInt(FunId.getText());
        String userName =  NomeUpdate.getText(); 
        FuncionarioDAO FunDao = new FuncionarioDAO();
        FunDao.removerFuncionario(id, userName);

        //lista novamente os usuarios mas atualizado
        DefaultTableModel table = (DefaultTableModel) FunTable.getModel();
        FunDao.listarFuncionarios(table);

    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void FuncUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FuncUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FuncUpdateActionPerformed

    private void homeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseClicked
        HomePageScreen homePage = new HomePageScreen();
        homePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeBtnMouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:

        VendaScreen telaVenda = new VendaScreen();
        telaVenda.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        // TODO add your handling code here:

        GerenciarProdutos prodScreen = new GerenciarProdutos();
        prodScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu5MouseClicked

    private void MenuGerenciarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuGerenciarFuncActionPerformed
        // TODO add your handling code here:

        GerenciarFuncionarios BuscarFunScreen = new GerenciarFuncionarios();
        BuscarFunScreen.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_MenuGerenciarFuncActionPerformed

    private void MenuCadastrarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastrarFuncActionPerformed
        // TODO add your handling code here:
        CadFuncionario CadFunScreen = new CadFuncionario();
        CadFunScreen.setVisible(true);
        //fecha tela atual
        this.dispose();
    }//GEN-LAST:event_MenuCadastrarFuncActionPerformed

    private void backupBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backupBtnMouseClicked
        // TODO add your handling code here:

        BackUpScreen backup = new BackUpScreen();
        backup.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backupBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GerenciarFuncionarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BuscarFunScreen;
    private javax.swing.JTextPane CpfUpdate;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JLabel FunId;
    private javax.swing.JTable FunTable;
    private javax.swing.JComboBox<String> FuncUpdate;
    private javax.swing.JTextPane IdPesquisa;
    private javax.swing.JMenuItem MenuCadastrarFunc;
    private javax.swing.JMenu MenuFunc;
    private javax.swing.JMenuItem MenuGerenciarFunc;
    private javax.swing.JTextPane NomeFunPesquisa;
    private javax.swing.JTextPane NomeUpdate;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JPanel UpdatesPanel;
    private javax.swing.JLabel atualFun;
    private javax.swing.JMenu backupBtn;
    private javax.swing.JMenu homeBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel revokeFunc;
    private javax.swing.JTextPane senhaUpdate;
    // End of variables declaration//GEN-END:variables
}
